version: "3"
services:
  node:
    container_name: node
    build: 
      context: .
      dockerfile: Dockerfile_node
    volumes:
      - ./app:/usr/app:cached
    command: sh -c "PORT=3000 npm start"
    tty: true
    ports:
      - "3000:3000"

    restart: always
